# Site settings
title: UPE at Mizzou
email: ""
description: >- # this means to ignore newlines until "baseurl:"
        Upsilon Pi Epsilon at the University of Missouri - Columbia
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  ""

# Build settings
markdown: kramdown
highlight: rouge

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
